//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPaswords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KayitTalep
    {
        public int ID { get; set; }
        public string isim_soyisim { get; set; }
        public string mail { get; set; }
        public Nullable<bool> adminMi { get; set; }
        public bool durum { get; set; }
        public string aciklama { get; set; }
    }
}
