//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPaswords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Kategori_Talep = new HashSet<Kategori_Talep>();
            this.Sifres = new HashSet<Sifre>();
        }
    
        public int ID { get; set; }
        public string Mail { get; set; }
        public string Sifre { get; set; }
        public string IsimSoyisim { get; set; }
        public Nullable<System.DateTime> KayıtTarih { get; set; }
        public Nullable<System.DateTime> SonGiris { get; set; }
        public string Token { get; set; }
        public int RolID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategori_Talep> Kategori_Talep { get; set; }
        public virtual Yetki Yetki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sifre> Sifres { get; set; }
    }
}
