//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPaswords.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sifre
    {
        public int ID { get; set; }
        public int Kullanici_ID { get; set; }
        public string KayıtliSifre { get; set; }
        public string Aciklama { get; set; }
        public int Kategori_ID { get; set; }
        public bool Durum { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
